---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: web-instance
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible
    #image: docker.io/geerlingguy/docker-rockylinux9-ansible
    #image: docker.io/geerlingguy/docker-rockylinux8-ansible
    #image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    #image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    #image: docker.io/geerlingguy/docker-debian11-ansible
    #image: docker.io/geerlingguy/docker-debian10-ansible
    #image: docker.io/geerlingguy/docker-fedora36-ansible
    #image: docker.io/geerlingguy/docker-fedora35-ansible
    #image: quay.io/centos/centos:stream8
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true 
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
