---
name: CI
'on':
  pull_requests:
  push:
    branches:
      - master
      - main

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkouts@v2

      - name: Setup Python3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependences.
        run: pip3 install molecule docker yamllint ansible-lint

      - name: Run molecule tests.
        run: molecule test
